apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eudistack-issuer-enterprise-backend.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "eudistack-issuer-enterprise-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eudistack-issuer-enterprise-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eudistack-issuer-enterprise-backend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eudistack-issuer-enterprise-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ include "eudistack-issuer-enterprise-backend.serverPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ include "eudistack-issuer-enterprise-backend.serverPort" . }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ include "eudistack-issuer-enterprise-backend.serverPort" . }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: {{ .Values.app.profile }}
            - name: SIGNING_PROVIDER
              value: {{ .Values.app.signing.provider }}
            - name: SIGNING_CORE_URL
              value: {{ .Values.app.signing.coreUrl }}
            - name: REMOTE_SIGNATURE_TYPE
              value: "{{ .Values.app.remoteSignature.type }}"
            - name: REMOTE_SIGNATURE_URL
              value: { { .Values.app.remoteSignature.url } }
            - name: REMOTE_SIGNATURE_CREDENTIAL_ID
              valueFrom:
                secretKeyRef:
                  name: { { include "eudistack-issuer-core-backend.remoteSignature-secretName" . } }
                  key: { { include "eudistack-issuer-core-backend.remoteSignature-credentialId" . } }
            - name: REMOTE_SIGNATURE_CREDENTIAL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: { { include "eudistack-issuer-core-backend.remoteSignature-secretName" . } }
                  key: { { include "eudistack-issuer-core-backend.remoteSignature-credentialPassword" . } }
            - name: REMOTE_SIGNATURE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: { { include "eudistack-issuer-core-backend.remoteSignature-secretName" . } }
                  key: { { include "eudistack-issuer-core-backend.remoteSignature-clientId" . } }
            - name: REMOTE_SIGNATURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: { { include "eudistack-issuer-core-backend.remoteSignature-secretName" . } }
                  key: { { include "eudistack-issuer-core-backend.remoteSignature-clientSecret" . } }
