{{- if not .Values.app.remoteSignature.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eudistack-issuer-enterprise-backend.remoteSignature-secretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "eudistack-issuer-enterprise-backend.labels" . | nindent 4 }}
type: Opaque
data:
  remote-signature-client-id: {{ .Values.app.remoteSignature.clientId | b64enc }}
  remote-signature-client-secret: {{ .Values.app.remoteSignature.clientSecret | b64enc }}
  remote-signature-credential-id: {{ .Values.app.remoteSignature.credentialId | b64enc }}
  remote-signature-credential-password: {{ .Values.app.remoteSignature.credentialPassword | b64enc }}
{{- end }}