apiVersion: v1
kind: Service
metadata:
  name: {{ include "isbe-csc-frontend.fullname" . }}
  labels:
    {{- include "isbe-csc-frontend.labels" . | nindent 4 }}
    # Etiqueta clave que usará el ServiceMonitor para encontrar este servicio
    app: {{ include "isbe-csc-frontend.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    # Puerto para que Prometheus recoja las métricas
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "isbe-csc-frontend.selectorLabels" . | nindent 4 }}
