global:
  domain: "127.0.0.1.nip.io"
  ingress:
    enabled: false
    className: "nginx-acme"
    labels: {}
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    enableTLS: true
    clusterIssuer: "letsencrypt"