apiVersion: v2
name: issuer-api
description: A Helm chart for Kubernetes
type: application
version: 0.7.0
appVersion: v0.7.0

sources:
  - https://github.com/in2workspace/issuer-api

maintainers:
  - name: Oriol Canad√©s
    email: oriol.canades@in2.es
