apiVersion: v1
kind: Secret
metadata:
  name: eudistack-issuer-sealed-secret
  namespace:  {{ .Release.Namespace }}
data:
  postgres-password: "" # base64 encoded secret
  remote-signature-client-id: "" # base64 encoded secret
  remote-signature-client-secret: "" # base64 encoded secret
  remote-signature-credential-id: "" # base64 encoded secret
  remote-signature-credential-password: "" # base64 encoded secret
  default-signer-common-name: "" # base64 encoded secret
  default-signer-country: "" # base64 encoded secret
  default-signer-email: "" # base64 encoded secret
  default-signer-organization: "" # base64 encoded secret
  default-signer-organization-identifier: "" # base64 encoded secret
  default-signer-serial-number: "" # base64 encoded secret
  auth-server-password: "" # base64 encoded secret
  mail-username: "" # base64 encoded secret
  mail-password: "" # base64 encoded secret
  issuer-identity-vc: "" # base64 encoded secret
  issuer-identity-private-key: "" # base64 encoded secret
  issuer-identity-credential-did-key: "" # base64 encoded secret