global:
  domain: "localhost"
  ingress:
    enabled: true
    className: "nginx"
    labels: {}
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    enableTLS: false
    clusterIssuer: "letsencrypt-in2-test-issuer"

## configuration for the eudistack-wallet-enterprise-backend
eudistack-wallet-enterprise-backend:
  fullnameOverride: "eudistack-wallet-enterprise-backend"
  image:
    # -- image pull policy
    pullPolicy: Always
    # -- image tag
    tag: v1.4.4
  # ingress specific configuration
  ingress:
    enabled: false
  # scripts before container initializes

  app:
    logLevel: DEBUG
    authServer:
      externalUrl: http://localhost/keycloak/realms/wallet
      internalUrl: http://eudistack-wallet-keycloak:80/realms/wallet
    cors:
      # expects a string of url's separated with comma and space
      allowedOrigins: "http://localhost.com, https://localhost.com, www.example-cors-two.com"
    vault:
      provider: hashicorp
      url: http://vault-server:8200
      secretsMount: kv
      token: defaultToken
      existingSecret:
        # -- should an existing secret be used
        enabled: false
        # -- name of the secret
        name: eudistack-wallet-sealed-secret
        # -- key to retrieve the token from
        key: vault-token
    ebsiTest:
      # this will fail in the API unless the specified realm, client and user-password are created in the Keycloak instance
      url: http://eudistack-wallet-keycloak:80/realms/wallet/protocol/openid-connect/token
      client:
        id: user-registry-client
        secret: defaultSecret
        existingSecret:
          # -- should an existing secret be used
          enabled: false
          # -- name of the secret
          name: eudistack-wallet-sealed-secret
          # -- key to retrieve the password from
          key: ebsi-client-secret
      userData:
        name: admin
        password: defaultPassword
        existingSecret:
          # -- should an existing secret be used
          enabled: false
          # -- name of the secret
          name: eudistack-wallet-sealed-secret
          # -- key to retrieve the password from
          key: ebsi-user-password
    db:
      schema: wallet
      host: wallet-postgres
      port: 5432
      name: wallet
      username: postgres
      password: postgres
      ssl:
        enabled: false
        mode: require
      existingSecret:
        enabled: false
        name: eudistack-wallet-sealed-secret
        key: password

## configuration for the eudistack-wallet-core-frontend
eudistack-wallet-core-frontend:
  fullnameOverride: "eudistack-wallet-core-frontend"
  # -- image pull policy
  pullPolicy: Always
  # -- image tag
  tag: v2.0.0
  ## ingress specific configuration
  ingress:
    enabled: false
  ## deployment specific configuration
  app:
    logsEnabled: false
    colors:
      primary: "#00ADD3"
      primaryContrast: "#ffffff"
      secondary: "#50c8ff"
      secondaryContrast: "#50c8ff"
    assets:
      baseUrl: "assets"
      logoPath: "logos/no-image.png"
      faviconPath: "icons/altia-favicon.ico"
    defaultLang: "en"
    walletApi:
      externalUrl: http://localhost
      websocketExternalUrl: ws://localhost
    iam:
      externalUrl: http://localhost/keycloak/realms/wallet

## configuration for the eudistack-wallet-keycloak
eudistack-wallet-keycloak:
  nameOverride: eudistack-wallet-keycloak
  fullnameOverride: eudistack-wallet-keycloak
  # -- should be enabled?
  enabled: true
  ## ingress specific configuration
  ingress:
    enabled: true
    className: nginx
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: localhost
        paths:
          - path: /keycloak(/|$)(.*)
            pathType: ImplementationSpecific
    tls: []

  app:
    keycloak:
      hostnameUrl: "http://localhost/keycloak"
      adminUrl: "http://localhost/keycloak"
      admin: admin
      password: admin
      existingSecret:
        # -- should an existing secret be used
        enabled: false
        # -- name of the secret
        name: eudistack-wallet-sealed-secret
        # -- key to retrieve the password from
        key: keycloak-password
      mail:
        host: smtp.example.org
        port: 587
        from: example@example.org
        fromDisplayName: Example
        replyTo: example@example.org
        username: user
        password: password
        existingSecret:
          enabled: false
          name: mail-secret
          userKey: mail-user
          passwordKey: mail-password
        properties:
          mail:
            smtp:
              auth: true
              starttls:
                enable: true
              ssl:
                enable: false
    db:
      type: postgres
      host: eudistack-wallet-keycloak-postgres
      port: 5432
      name: keycloak
      username: postgres
      password: postgres
      existingSecret:
        # -- should an existing secret be used
        enabled: false
        # -- name of the secret
        name: eudistack-wallet-sealed-secret
        # -- key to retrieve the password from
        key: keycloak-db-password

## configuration of postgres to be used for the blockchain-connector - see https://github.com/bitnami/charts/tree/main/bitnami/postgresql for details
eudistack-wallet-keycloak-postgresql:
  # -- should the postgresql deployment be enabled
  enabled: true
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  # ! Changing this parameter may cause the PVC to be re-created and the data lost
  fullnameOverride: eudistack-wallet-keycloak-postgres
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  # ! Changing this parameter may cause the PVC to re-created and the data lost
  nameOverride: eudistack-wallet-keycloak-postgres
  ## network policy configuration
  networkPolicy:
    enabled: false
  ## persistence volume claim configuration retention policy
  persistentVolumeClaimRetentionPolicy:
    enabled: true
    whenScaled: Retain
    whenDeleted: Retain
  ## auth configuration for the database
  auth:
    # -- username to be used
    username: postgres
    # -- should the default postgres user be enabled
    enablePostgresUser: true
    # -- password to be used
    password: postgres
  ## configuration of the postgres primary replica
  primary:
    # Configuration for Velero backup
    annotations:
      backup.velero.io/backup-volumes: data
    podAnnotations:
      backup.velero.io/backup-volumes: data
    ## provide db initialization
    initdb:
      ## provide scripts for initialization
      scripts:
        # -- create the database as expected by the blockchain-connector
        create.sh: |
          psql postgresql://postgres:${POSTGRES_PASSWORD}@localhost:5432 -c "CREATE DATABASE keycloak;"
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.2.0-debian-12-r8
    pullPolicy: IfNotPresent

## configuration of postgres
eudistack-wallet-postgresql:
  # -- should the postgresql deployment be enabled
  enabled: true
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  # ! Changing this parameter may cause the PVC to re-created and the data lost
  fullnameOverride: wallet-postgres
  # -- overrides the generated name, provides stable service names - this should be avoided if multiple instances are available in the same namespace
  # ! Changing this parameter may cause the PVC to re-created and the data lost
  nameOverride: wallet-postgres
  ## auth configuration for the database
  auth:
    # -- username to be used
    username: postgres
    # -- should the default postgres user be enabled
    enablePostgresUser: true
    # -- password to be used
    password: postgres
    # -- database name to be used
    database: wallet
  ## configuration of the postgres primary replica
  primary:
    # Configuration for Velero backup
    annotations:
      backup.velero.io/backup-volumes: data
    podAnnotations:
      backup.velero.io/backup-volumes: data
    ## network policy configuration
    networkPolicy:
      enabled: false
    ## persistence volume claim configuration retention policy
    persistentVolumeClaimRetentionPolicy:
      enabled: true
      whenScaled: Retain
      whenDeleted: Retain
  global:
    security:
      allowInsecureImages: true
  image:
    registry: docker.io
    repository: bitnamilegacy/postgresql
    tag: 17.2.0-debian-12-r8
    pullPolicy: IfNotPresent
