apiVersion: v1
kind: Service
metadata:
  name: {{ include "eudistack-issuer-frontend.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "eudistack-issuer-frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "eudistack-issuer-frontend.serverPort" . }}
      {{ if eq .Values.service.type "NodePort" }}
      nodePort: 30000
      {{ end }}
      protocol: TCP
      name: http
  selector:
    {{- include "eudistack-issuer-frontend.selectorLabels" . | nindent 4 }}