apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eudistack-wallet-core-frontend.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "eudistack-wallet-core-frontend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eudistack-wallet-core-frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eudistack-wallet-core-frontend.labels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eudistack-wallet-core-frontend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ include "eudistack-wallet-core-frontend.serverPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ include "eudistack-wallet-core-frontend.serverPort" . }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ include "eudistack-wallet-core-frontend.serverPort" . }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: LOGS_ENABLED
              value: {{ quote .Values.app.logsEnabled }}
            - name: PRIMARY
              value: {{ .Values.app.colors.primary | quote }}
            - name: PRIMARY_CONTRAST
              value: {{ .Values.app.colors.primaryContrast | quote }}
            - name: SECONDARY
              value: {{ .Values.app.colors.secondary | quote }}
            - name: SECONDARY_CONTRAST
              value: {{ .Values.app.colors.secondaryContrast | quote }}
            - name: ASSETS_BASE_URL
              value: {{ .Values.app.assets.baseUrl }}
            - name: LOGO_PATH
              value: {{ .Values.app.assets.logoPath }}
            - name: FAVICON_PATH
              value: {{ .Values.app.assets.faviconPath }}
            - name: WALLET_API_EXTERNAL_URL
              value: {{.Values.app.walletApi.externalUrl}}
            - name: WALLET_API_WEBSOCKET_EXTERNAL_URL
              value: {{.Values.app.walletApi.websocketExternalUrl}}
            - name: IAM_EXTERNAL_URL
              value: {{.Values.app.iam.externalUrl}}
            - name: DEFAULT_LANG
              value: {{.Values.app.defaultLang}}