apiVersion: v2
name: eudistack-issuer
description: Parent chart managing all the components of the Credential Issuer application

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.1

dependencies:
  - name: eudistack-issuer-core-backend
    version: 1.0.0

  - name: eudistack-issuer-enterprise-backend
    version: 1.0.1

  - name: eudistack-issuer-frontend
    version: 1.0.0

  - name: postgresql
    version: 13.1.5
    repository: oci://registry-1.docker.io/bitnamicharts
    alias: eudistack-issuer-postgresql
    condition: eudistack-issuer-postgresql.enabled