apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "app-example-chart.fullname" . }}
  labels:
    {{- include "app-example-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "app-example-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "app-example-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: {{ .Values.service.metricsPortName }}
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          # Argumentos para el exporter de Nginx, para que apunte a un Nginx local (no incluido aquí para simplicidad)
          # En una app real, el exporter estaría junto al proceso principal.
          args:
            - -nginx.scrape-uri=http://127.0.0.1/stub_status
          resources:
            {{- toYaml .Values.resources | nindent 12 }}