{{- if .Values.observability.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "app-example-chart.fullname" . }}-rules
  labels:
    {{- include "app-example-chart.labels" . | nindent 4 }}
    # Etiqueta para que el Prometheus Operator descubra estas reglas
    release: prometheus
spec:
  groups:
  - name: {{ include "app-example-chart.name" . }}.rules
    rules:
    - alert: {{ .Values.appName | title }}Down
      expr: up{job="{{ include "app-example-chart.fullname" . }}"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "El exporter de {{ .Values.appName }} está caído"
        description: "Prometheus no ha podido recoger métricas del job {{`{{ $labels.job }}`}} durante más de 2 minutos."
{{- end }}