apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eudistack-wallet-enterprise-backend.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "eudistack-wallet-enterprise-backend.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "eudistack-wallet-enterprise-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "eudistack-wallet-enterprise-backend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      # scripts before container initializes
      # todo: maybe find another way to do this
      initContainers:
        {{- toYaml .Values.initContainers | nindent 8 }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "eudistack-wallet-enterprise-backend.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ include "eudistack-wallet-enterprise-backend.serverPort" . }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ include "eudistack-wallet-enterprise-backend.serverPort" . }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ include "eudistack-wallet-enterprise-backend.serverPort" . }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          env:
            - name: SERVER_PORT
              value: {{ include "eudistack-wallet-enterprise-backend.serverPort" . | quote }}
            - name: SPRING_WEBFLUX_BASE_PATH
              value: /
            - name: LOGGING_LEVEL_ES_IN2_WALLET_API
              value: {{ .Values.app.logLevel }}
            # AUTH SERVER
            - name: SECURITY_AUTH_SERVER_EXTERNAL_URL
              value: {{ .Values.app.authServer.externalUrl }}
            - name: SECURITY_AUTH_SERVER_INTERNAL_URL
              value: {{ .Values.app.authServer.internalUrl }}
            # CORS
            - name: SECURITY_CORS_ALLOWED_ORIGINS
              value: {{ .Values.app.cors.allowedOrigins }}
            # VAULT
            - name: SECURITY_VAULT_PROVIDER_NAME
              value: {{ .Values.app.vault.provider }}
            - name: SECURITY_VAULT_HASHICORP_URL
              value: {{ .Values.app.vault.url }}
            - name: SECURITY_VAULT_HASHICORP_SECRETS_MOUNT
              value: {{ .Values.app.vault.secretsMount }}
            - name: SECURITY_VAULT_HASHICORP_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "eudistack-wallet-enterprise-backend.vaultTokenSecretName" . }}
                  key: {{ include "eudistack-wallet-enterprise-backend.vaultTokenSecretKey" . }}
            # EBSI TESTS
            - name: EBSI_TEST_URL
              value: {{ .Values.app.ebsiTest.url }}
            - name: EBSI_TEST_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "eudistack-wallet-enterprise-backend.ebsiClientSecretName" . }}
                  key: {{ include "eudistack-wallet-enterprise-backend.ebsiClientSecretKey" . }}
            - name: EBSI_TEST_CLIENT_ID
              value: {{ .Values.app.ebsiTest.client.id }}
            - name: EBSI_TEST_USERNAME
              value: {{ .Values.app.ebsiTest.userData.name }}
            - name: EBSI_TEST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "eudistack-wallet-enterprise-backend.ebsiUserSecretName" . }}
                  key: {{ include "eudistack-wallet-enterprise-backend.ebsiUserSecretKey" . }}
            # DATABASE
            - name: SPRING_R2DBC_URL
              value: "r2dbc:postgresql://{{ .Values.app.db.host }}:{{ .Values.app.db.port }}/{{ .Values.app.db.name }}?ssl={{ .Values.app.db.ssl.enabled }}&sslmode={{ .Values.app.db.ssl.mode }}&schema={{ .Values.app.db.schema }}"
            - name: SPRING_R2DBC_USERNAME
              value: {{ .Values.app.db.username }}
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "eudistack-wallet-enterprise-backend.dbSecretName" . }}
                  key: {{ include "eudistack-wallet-enterprise-backend.dbSecretKey" . }}
            - name: SPRING_FLYWAY_URL
              value: "jdbc:postgresql://{{ .Values.app.db.host }}:{{ .Values.app.db.port }}/{{ .Values.app.db.name }}?schema={{ .Values.app.db.schema }}"
            - name: SPRING_FLYWAY_USER
              value: {{ .Values.app.db.username }}
            - name: SPRING_FLYWAY_DEFAULT_SCHEMA
              value: {{ .Values.app.db.schema }}
            - name: SPRING_FLYWAY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "eudistack-wallet-enterprise-backend.dbSecretName" . }}
                  key: {{ include "eudistack-wallet-enterprise-backend.dbSecretKey" . }}