apiVersion: v1
kind: Service
metadata:
  name: {{ include "isbe-certauth.fullname" . }}
  labels:
    {{- include "isbe-certauth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.certauth }}
      targetPort: certauth
      protocol: TCP
      name: certauth
    - port: {{ .Values.service.ports.certsec }}
      targetPort: certsec
      protocol: TCP
      name: certsec
    - port: {{ .Values.service.ports.onboard }}
      targetPort: onboard
      protocol: TCP
      name: onboard
  selector:
    {{- include "isbe-certauth.selectorLabels" . | nindent 4 }}
