apiVersion: v2
name: desmos
description: A Helm chart for Kubernetes
type: application
version: 0.5.0
appVersion: v0.5.0

sources:
  - https://github.com/in2workspace/desmos

maintainers:
  - name: Oriol Canad√©s
    email: oriol.canades@in2.es
