{{- if or
    (not .Values.app.db.existingSecret.enabled)
    (not .Values.app.keycloak.existingSecret.enabled)
    (not .Values.app.keycloak.mail.existingSecret.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "eudistack-wallet-keycloak.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "eudistack-wallet-keycloak.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if not .Values.app.db.existingSecret.enabled }}
  keycloak-db-password: {{ .Values.app.db.password | b64enc }}
  {{- end }}

  {{- if not .Values.app.keycloak.existingSecret.enabled }}
  keycloak-password: {{ .Values.app.keycloak.password | b64enc }}
  {{- end }}

  {{- if not .Values.app.keycloak.mail.existingSecret.enabled }}
  mail-username: {{ .Values.app.keycloak.mail.username | b64enc }}
  mail-password: {{ .Values.app.keycloak.mail.password | b64enc }}
  {{- end }}
{{- end }}
