apiVersion: v1
kind: Service
metadata:
  name: {{ include "eudistack-wallet-keycloak.fullname" . }}
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "eudistack-wallet-keycloak.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ include "eudistack-wallet-keycloak.serverPort" . }}
      protocol: TCP
      name: http
  selector:
    {{- include "eudistack-wallet-keycloak.selectorLabels" . | nindent 4 }}
