{{- if .Values.ingressIssuerApi.enabled -}}
  {{- $fullName := include "eudistack-issuer-core-backend.fullname" . -}}
  {{- $servicePort := .Values.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-issuer-api
  labels:
    {{ include "eudistack-issuer-core-backend.labels" . | nindent 4 }}
  {{- if .Values.ingressIssuerApi.annotations }}
  annotations:
    {{- with .Values.ingressIssuerApi.annotations }}
      {{- toYaml . | nindent 4 }}
      {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingressIssuerApi.className }}
  ingressClassName: {{ .Values.ingressIssuerApi.className }}
  {{- end }}
  {{- if .Values.ingressIssuerApi.tls }}
  tls:
    {{- range .Values.ingressIssuerApi.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
  {{- range .Values.ingressIssuerApi.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
      {{- range .paths }}
          - path: {{ .path | quote }}
            pathType: {{ .pathType | quote }}
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $servicePort }}
      {{- end }}
  {{- end }}
  {{- end }}